#### adress of the data 



addr_cam = 'FLASH.DIAG/CAMERA/OTR9FL2XTDS/';
addr_cam_data = 'FLASH.DIAG/CAMERA/OTR9FL2XTDS/IMAGE_EXT_ZMQ'
addr_TDSphase='FLASH.RF/LLRF.CONTROLLER/CTRL.POLARIX/SP.PHASE';
addr_COFM='FLASH.DIAG/CAMERA/OTR9FL2XTDS/SPECTRUM.X.CM'
addr='FLASH.DIAG/CAMERA/OTR9FL2XTDS/SPECTRUM.X.MEAN';
addr_dipol='FLASH.MAGNETS/MAGNET.ML/D4FL2XTDS/CURRENT.SP';

chageaddr='FLASH.DIAG/TOROID/7FL2XTDS/CHARGE.FLASH2'
addr_bpmx='FLASH.DIAG/BPM/9FL2XTDS/X.FLASH2'
addr_bpmy='FLASH.DIAG/BPM/9FL2XTDS/Y.FLASH2'
compressionTD11='FLASH.SDIAG/BCM/FL0.DBC1.1/COMPRESSION.normalized.TD'
compressionTD12='FLASH.SDIAG/BCM/FL0.DBC1.2/COMPRESSION.normalized.TD'
compressionTD21='FLASH.SDIAG/BCM/FL0.DBC2.1/COMPRESSION.normalized.TD'
compressionTD22='FLASH.SDIAG/BCM/FL0.DBC2.2/COMPRESSION.normalized.TD'
compressionTD51='FLASH.SDIAG/BCM/FL2.SEED5.1/COMPRESSION.normalized.TD'
compressionTD52='FLASH.SDIAG/BCM/FL2.SEED5.2/COMPRESSION.normalized.TD'
BAMUBC1='FLASH.SDIAG/BAM/FL0.UBC1/ARRIVAL_TIME.relative.TD'
BAMseed5='FLASH.SDIAG/BAM/FL2.SEED5/ARRIVAL_TIME.relative.TD'

XFGM_DP='FLASH.FEL/XGM.INTENSITY/FL2.TUNNEL/INTENSITY.RAW.TRAIN'
